version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper

  log-listener:
    build: ./log-listener
    image: nginx:latest

  log-processing:
    build: ./log-processing

  telemetry:
    build:  ./telemetry

  web-server:
    build: ./web-server
    ports:
      - "8080:8080"

  web-app:
    build: ./web-app
    ports:
      - "8080:8080"
    depends_on:
      - web-server
